### ISSUE TITLE
deployment of i-want-a-jobby change

### ISSUE THREAD

**Issue by ajhelmstetter** [RBGKew/bioinfo-utils#4]
I've added the ability to use 'status' as an argument to print the jobs list, but now this needs to be deployed on all machines (I've done it for senecio where I am able)

**Comment by ajhelmstetter** [comment]
Fixed a bug, still needs to be deployed

**Comment by pwkooij** [comment]
Pulled the changes to all boxes, except Equisetum atm (still need to setup the git repository there). Also, removed the program from the /usr/bin folder and created symlinks instead. This will it will automatically update whenever we pull a new version.

**Comment by lonelyjoeparker** [comment]
Awesome @pwkooij thanks!
@ajhelmstetter can we close #4 then yep?

**Comment by pwkooij** [comment]
now also on Equisetum. @ajhelmstetter did you implement any changes on the "unset" rules? As in, when you want to add the number of threads but not the memory, with the older version it would not show either of the two.

**Comment by ajhelmstetter** [comment]
@pwkooij I did not, could be worth it, or just force people to put in mem :)
@lonelyjoeparker yes, we can!
