### ISSUE TITLE
Add new cluster details to summary 

### ISSUE THREAD

**Issue by lonelyjoeparker** [RBGKew/bioinfo-utils#5]
In https://github.com/RBGKew/bioinfo-utils/blob/master/docs/Machines.md and create https://github.com/RBGKew/bioinfo-utils/blob/master/docs/Machines/Atta.md (e.g.)

**Comment by lonelyjoeparker** [comment]
Hi James, if you get a minute pls can you add the cluster to the table in https://github.com/RBGKew/bioinfo-utils/blob/master/docs/Machines.md ? cheers :)

**Comment by james-milburn-crowe** [comment]
sure! I have some docs to put up too, I 've just got to edit them a bit first

________________________________
